name: "Setup UV"
description: "Install uv, Python, and sync dependencies"
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.11"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash
    - name: Install dependencies
      run: uv sync --all-extras --dev
      shell: bash
